const neightbour = [
  {name: 'Jardim Margarida', days: [1, 3, 5], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Vila Nunes', days: [1, 3, 5], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Vila Brito', days: [1, 3, 5], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Santa Edwiges', days: [1, 3, 5], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Vila Passos', days: [1, 3, 5], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Parque Rodovia', days: [1, 3, 5], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Horto Florestal', days: [1, 3, 5], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Vila Esperança', days: [1, 3, 5], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Vila Simão', days: [1, 3, 5], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Vila Fabiano', days: [1, 3, 5], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Santa Rita', days: [1, 3, 5], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Novo Horizonte', days: [1, 3, 5], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Bairro da Cruz', days: [1, 3, 5], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Vila Zélia', days: [1, 3, 5], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Vila Celeste', days: [1, 3, 5], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Vila Maria', days: [1, 3, 5], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Vila Buck', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Vila Cida', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'São Roque', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Bairro S. Antônio', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Vila Neide', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Vila Diva', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Vila Rica', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'CECAP Baixa', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'CECAP Alta', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Jd. Primavera', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Vl. Comerciários I e II', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Portal das Palmeiras', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Cidade Industrial', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Pq. Mondesir', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Pq. Tabatinga', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Campo dos Ypes', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Aldo Nassif', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Brisa do Campo', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Olaria', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Vila Hepacaré', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Vila Figueira', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Village das Palmeiras', days: [2, 4, 6], details: 'COLETA DIURNA – INÍCIO ÀS 06h'},
  {name: 'Nova Lorena', days: [1, 3, 5], details: 'COLETA NOTURNA – INÍCIO ÀS 16h'},
  {name: 'Ponte Nova', days: [2, 4, 6], details: 'COLETA NOTURNA – INÍCIO ÀS 16h'},
  {name: 'Cabelinha', days: [2, 4, 6], details: 'COLETA NOTURNA – INÍCIO ÀS 16h'},
  {name: 'Campinho ', days: [3], details: 'BAIRRO COM FREQUÊNCIA ESPECÍFICA: Noturno'},
  {name: 'Santa Lucrécia', days: [3, 6], details: 'BAIRRO COM FREQUÊNCIA ESPECÍFICA: Diurno'},
  {name: 'Aterrado', days: [2, 4], details: 'BAIRRO COM FREQUÊNCIA ESPECÍFICA: Diurno'},
  {name: 'Centro', days: [1, 6], details: 'COLETA NOTURNA / DIÁRIA – SEGUNDA A SÁBADO'},
  {name: 'Av. Dr. Peixoto de Castro', days: [1, 6], details: 'COLETA NOTURNA / DIÁRIA – SEGUNDA A SÁBADO'},
  {name: 'Av. São José', days: [1, 6], details: 'COLETA NOTURNA / DIÁRIA – SEGUNDA A SÁBADO'}
]

export default neightbour
